const products=[
 {id:1,cat:'armas',name:'Taurus TS9',short:'Pistola semiautomática com design ergonômico.',price:'Consulte',img:'assets/product-pistol.jpeg',desc:'Modelo para uso esportivo e defesa, com empunhadura ergonômica e construção robusta. Disponibilidade, calibre e configuração sujeitos ao estoque e à autorização legal.',specs:[['Categoria','Pistola'],['Disponibilidade','Sob consulta'],['Aquisição','Documentação obrigatória']]},
 {id:2,cat:'armas',name:'Carabina Lever Action',short:'Estilo clássico, acabamento em madeira.',price:'Consulte',img:'assets/product-carbine.jpeg',desc:'Carabina de ação por alavanca com visual clássico e acabamento em madeira. Consulte a equipe para especificações do exemplar, disponibilidade e processo documental.',specs:[['Categoria','Carabina'],['Ação','Alavanca'],['Aquisição','Documentação obrigatória']]},
 {id:3,cat:'armas',name:'Rifle Puma',short:'Plataforma longa para uso esportivo.',price:'Consulte',img:'assets/product-rifle.jpeg',desc:'Arma longa apresentada no catálogo da loja, indicada para consulta com atendimento especializado. Especificações e condições devem ser confirmadas presencialmente.',specs:[['Categoria','Arma longa'],['Estoque','Confirmar na loja'],['Aquisição','Documentação obrigatória']]},
 {id:4,cat:'armas',name:'Espingarda Pump',short:'Construção robusta e configuração tática.',price:'Consulte',img:'assets/product-shotgun.jpeg',desc:'Espingarda de ação pump em estojo rígido. O modelo, calibre e demais características devem ser confirmados com a equipe responsável.',specs:[['Categoria','Espingarda'],['Ação','Pump'],['Aquisição','Documentação obrigatória']]},
 {id:5,cat:'equipamentos',name:'Mochila Assault 44L',short:'Espaço, organização e resistência para a rotina.',price:'Consulte',img:'assets/product-backpack.jpeg',desc:'Mochila funcional em tom coyote, com múltiplos compartimentos, fitas modulares e capacidade aproximada de 44 litros. Ideal para trilhas, trabalho e atividades outdoor.',specs:[['Capacidade','Aprox. 44 L'],['Cor','Coyote'],['Uso','Outdoor / tático']]},
 {id:6,cat:'equipamentos',name:'Bota Invictus Tractor',short:'Aderência e proteção em terrenos exigentes.',price:'Consulte',img:'assets/product-boots.jpeg',desc:'Bota de cano médio com estrutura reforçada e solado de alta tração. Pensada para longas jornadas, ambientes externos e uso profissional.',specs:[['Categoria','Calçado'],['Perfil','Outdoor / tático'],['Tamanhos','Consultar estoque']]},
 {id:7,cat:'cutelaria',name:'Faca Artesanal El Fierro',short:'Peça artesanal com cabo texturizado.',price:'Consulte',img:'assets/product-knife.jpeg',desc:'Faca artesanal com identidade marcante e acabamento cuidadoso. Consulte medidas, material da lâmina, bainha e disponibilidade da peça exibida.',specs:[['Categoria','Cutelaria'],['Produção','Artesanal'],['Disponibilidade','Sob consulta']]}
];
const grid=document.querySelector('#product-grid'),modal=document.querySelector('#product-modal'),content=document.querySelector('#modal-content');
function render(filter='todos'){grid.innerHTML=products.filter(p=>filter==='todos'||p.cat===filter).map(p=>`<article class="product-card"><div class="product-media"><img src="${p.img}" alt="${p.name}" loading="lazy"><span class="tag">${p.cat}</span></div><div class="product-info"><h3>${p.name}</h3><p>${p.short}</p><div class="price-row"><div class="price"><small>Valor</small><strong>${p.price}</strong></div><button class="details" data-id="${p.id}">Ver detalhes</button></div></div></article>`).join('')}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');render(b.dataset.filter)}));
grid.addEventListener('click',e=>{const btn=e.target.closest('.details');if(!btn)return;const p=products.find(x=>x.id==btn.dataset.id);content.innerHTML=`<div class="modal-layout"><div class="modal-gallery"><img src="${p.img}" alt="${p.name}"></div><div class="modal-copy"><span class="eyebrow">${p.cat}</span><h2>${p.name}</h2><p class="description">${p.desc}</p><ul class="specs">${p.specs.map(s=>`<li><span>${s[0]}</span><strong>${s[1]}</strong></li>`).join('')}</ul><div class="modal-price">${p.price}</div><div class="payment"><strong>Condições de pagamento</strong><small>Consulte opções à vista e parceladas diretamente com a loja. Itens controlados dependem de análise documental e requisitos legais.</small></div></div></div>`;modal.showModal()});
document.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
const menu=document.querySelector('.menu-btn'),nav=document.querySelector('#main-nav');menu.addEventListener('click',()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))});nav.addEventListener('click',()=>nav.classList.remove('open'));render();